-- ============================================================
-- RECALL AI — Complete Supabase SQL Setup
-- Run this ENTIRE file in: Supabase → SQL Editor → New Query
-- This creates everything needed for the Recall AI project
-- including AI auto-tagging and auto-summary support
-- ============================================================


-- ── STEP 1: CLEAN SLATE ──────────────────────────────────────
-- Drop existing tables if they exist so we start fresh
-- CASCADE means related data is also dropped

DROP TABLE IF EXISTS searches CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;


-- ── STEP 2: PROFILES TABLE ───────────────────────────────────
-- Stores one row per registered user

CREATE TABLE profiles (
  -- Unique ID for each user, auto-increments
  id           BIGSERIAL PRIMARY KEY,

  -- Full name entered during signup
  username     TEXT NOT NULL,

  -- Email address — must be unique across all users
  email        TEXT NOT NULL UNIQUE,

  -- Encrypted password (never stored as plain text)
  password     TEXT NOT NULL,

  -- Date and time the account was created
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ── STEP 3: SEARCHES TABLE ───────────────────────────────────
-- Stores every prompt/search the user saves
-- One user can have many searches (one-to-many)

CREATE TABLE searches (
  -- Unique ID for each search, auto-increments
  id           BIGSERIAL PRIMARY KEY,

  -- Links this search to a user in profiles table
  -- If the user is deleted, their searches are deleted too (CASCADE)
  user_id      BIGINT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,

  -- The actual prompt/search text the user typed
  query        TEXT NOT NULL,

  -- Which AI platform was used (ChatGPT, Claude etc.)
  source       TEXT NOT NULL DEFAULT 'ChatGPT',

  -- Category tag — auto-assigned by Gemini AI
  -- Options: Science, Tech, Health, Finance, History, Other
  tag          TEXT NOT NULL DEFAULT 'Other',

  -- Short summary — auto-generated by Gemini AI (max 12 words)
  summary      TEXT NOT NULL DEFAULT '',

  -- When the search was made (sent from Chrome extension)
  timestamp    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Whether this search has been shared publicly
  is_shared    BOOLEAN NOT NULL DEFAULT FALSE,

  -- Unique random token used in the public share link
  -- NULL means not shared yet
  share_token  TEXT UNIQUE DEFAULT NULL,

  -- When this row was created in the database
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ── STEP 4: DISABLE ROW LEVEL SECURITY ──────────────────────
-- Our Node.js backend uses the Supabase SERVICE ROLE KEY
-- which bypasses RLS automatically.
-- Security is handled in the backend code instead
-- (every query checks user_id to prevent cross-user access)

ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE searches DISABLE ROW LEVEL SECURITY;


-- ── STEP 5: CREATE INDEXES ───────────────────────────────────
-- Indexes make queries faster — like a book index

-- Speed up login (searching by email)
CREATE INDEX idx_profiles_email
  ON profiles(email);

-- Speed up fetching all searches for one user
CREATE INDEX idx_searches_user_id
  ON searches(user_id);

-- Speed up sorting by newest first
CREATE INDEX idx_searches_timestamp
  ON searches(timestamp DESC);

-- Speed up filtering by tag (e.g. only show "Science")
CREATE INDEX idx_searches_tag
  ON searches(tag);

-- Speed up looking up a shared search by token
CREATE INDEX idx_searches_share_token
  ON searches(share_token);

-- Speed up filtering shared vs private searches
CREATE INDEX idx_searches_is_shared
  ON searches(is_shared);

-- Speed up full text search on query and summary
CREATE INDEX idx_searches_query
  ON searches USING gin(to_tsvector('english', query));


-- ── STEP 6: VERIFY ───────────────────────────────────────────
SELECT 'profiles table created successfully ✅' AS status;
SELECT 'searches table created successfully ✅' AS status;
SELECT 'All indexes created successfully ✅'    AS status;


-- ── DONE ─────────────────────────────────────────────────────
-- Your Supabase database is fully ready!
--
-- profiles table columns:
--   id, username, email, password, created_at
--
-- searches table columns:
--   id, user_id, query, source, tag, summary,
--   timestamp, is_shared, share_token, created_at
--
-- Next step: Go to Supabase → Settings → API
-- Copy your Project URL and Service Role Key
-- Paste them into the backend .env file
-- ============================================================
